package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type envKey struct {
	Name string
	Desc string
	Help string // URL or hint for getting the key
}

var envKeys = []envKey{
	{"ETHERSCAN_API_KEY", "Gnosisscan (transaction sync)", "https://gnosisscan.io/myapikey"},
	{"DISCORD_BOT_TOKEN", "Discord (message sync)", "https://discord.com/developers/applications"},
	{"STRIPE_SECRET_KEY", "Stripe (member/transaction sync)", "https://dashboard.stripe.com/apikeys"},
	{"MONERIUM_CLIENT_ID", "Monerium OAuth client ID", "https://monerium.dev/docs/getting-started"},
	{"MONERIUM_CLIENT_SECRET", "Monerium OAuth client secret", "https://monerium.dev/docs/getting-started"},
	{"ODOO_URL", "Odoo instance URL", "e.g. https://mycompany.odoo.com"},
	{"ODOO_LOGIN", "Odoo login email", "The email you use to log into Odoo"},
	{"ODOO_PASSWORD", "Odoo password or API key", "Settings > API Keys (recommended)"},
}

// Setup runs the interactive key configuration wizard
func Setup() error {
	configPath := configEnvPath()
	existing := loadConfigEnv(configPath)
	reader := bufio.NewReader(os.Stdin)

	for {
		fmt.Printf("\n%sCommons Hub CLI Setup%s\n", Fmt.Bold, Fmt.Reset)
		fmt.Println("─────────────────────")
		fmt.Printf("%sRun `chb settings` to inspect or diff your configuration files.%s\n\n", Fmt.Dim, Fmt.Reset)

		for i, k := range envKeys {
			status := fmt.Sprintf("%s☐%s", Fmt.Dim, Fmt.Reset)
			if val, _, ok := resolveEnvValue(existing, k.Name); ok && val != "" {
				status = fmt.Sprintf("%s✓%s", Fmt.Green, Fmt.Reset)
			}
			fmt.Printf("  %d. %s  %-22s %s%s%s\n", i+1, status, k.Name, Fmt.Dim, k.Desc, Fmt.Reset)
		}

		// Nostr identity status
		nostrStatus := fmt.Sprintf("%s☐%s", Fmt.Dim, Fmt.Reset)
		nostrDesc := "Not configured"
		if keys := LoadNostrKeys(); keys != nil {
			nostrStatus = fmt.Sprintf("%s✓%s", Fmt.Green, Fmt.Reset)
			nostrDesc = fmt.Sprintf("%s (%d relays)", keys.Npub[:20]+"...", len(keys.Relays))
		}
		fmt.Printf("\n  n. %s  %-22s %s%s%s\n", nostrStatus, "Nostr Identity", Fmt.Dim, nostrDesc, Fmt.Reset)
		fmt.Printf("  o. %s  %-22s %s%s%s\n", fmt.Sprintf("%s·%s", Fmt.Dim, Fmt.Reset), "Odoo Category Mapping", Fmt.Dim, "Map Odoo analytic accounts to categories", Fmt.Reset)

		fmt.Println()
		fmt.Printf("Select key to configure (1-%d), or q to quit: ", len(envKeys))
		input, _ := reader.ReadString('\n')
		input = strings.TrimSpace(input)

		if input == "q" || input == "Q" || input == "" {
			fmt.Println()
			return nil
		}
		if input == "n" || input == "N" {
			SetupNostr()
			continue
		}
		if input == "o" || input == "O" {
			SetupOdoo()
			continue
		}

		idx := 0
		if _, err := fmt.Sscanf(input, "%d", &idx); err != nil || idx < 1 || idx > len(envKeys) {
			fmt.Printf("%sInvalid selection%s\n", Fmt.Red, Fmt.Reset)
			continue
		}

		k := envKeys[idx-1]
		fmt.Println()
		fmt.Printf("%s%s%s\n", Fmt.Bold, k.Name, Fmt.Reset)
		fmt.Printf("  %s%s%s\n", Fmt.Dim, k.Desc, Fmt.Reset)
		if k.Help != "" {
			fmt.Printf("  Get one at: %s%s%s\n", Fmt.Cyan, k.Help, Fmt.Reset)
		}

		// Show current value masked if set
		if val, source, ok := resolveEnvValue(existing, k.Name); ok && val != "" {
			masked := maskValue(val)
			fmt.Printf("  Current: %s%s (%s)%s\n", Fmt.Dim, masked, source, Fmt.Reset)
		}

		fmt.Println()
		fmt.Printf("  Paste key (or Enter to cancel): ")
		value, _ := reader.ReadString('\n')
		value = strings.TrimSpace(value)

		// Overwrite the input line to hide the pasted secret
		if value != "" {
			fmt.Printf("\033[1A\033[2K  Paste key (or Enter to cancel): %s\n", maskValue(value))
		}

		if value == "" {
			continue
		}

		existing[k.Name] = value
		if err := saveConfigEnv(configPath, existing); err != nil {
			fmt.Printf("  %sError saving:%s %v\n", Fmt.Red, Fmt.Reset, err)
			continue
		}

		fmt.Printf("  %s✓ Saved %s%s = %s%s%s\n", Fmt.Green, k.Name, Fmt.Reset, Fmt.Dim, maskValue(value), Fmt.Reset)
	}
}

func configEnvPath() string {
	return settingsFilePath("config.env")
}

func loadConfigEnv(path string) map[string]string {
	result := make(map[string]string)
	data, err := os.ReadFile(path)
	if err != nil {
		return result
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			val := strings.TrimSpace(parts[1])
			// Strip surrounding quotes
			val = strings.Trim(val, "\"'")
			result[key] = val
		}
	}
	return result
}

func saveConfigEnv(path string, env map[string]string) error {
	dir := filepath.Dir(path)
	os.MkdirAll(dir, 0755)

	var lines []string
	lines = append(lines, "# Commons Hub CLI configuration")
	lines = append(lines, "# Generated by: chb setup")
	lines = append(lines, "")

	for _, k := range envKeys {
		if val, ok := env[k.Name]; ok && val != "" {
			lines = append(lines, fmt.Sprintf("%s=%s", k.Name, val))
		}
	}
	lines = append(lines, "")

	return os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0600)
}

func resolveEnvValue(config map[string]string, key string) (value, source string, ok bool) {
	if val := os.Getenv(key); val != "" {
		return val, "env", true
	}
	if val, ok := config[key]; ok && val != "" {
		return val, "config.env", true
	}
	return "", "", false
}

// LoadEnvFromConfig loads APP_DATA_DIR/settings/config.env into os environment
// if not already set.
func LoadEnvFromConfig() {
	for key, val := range loadConfigEnv(configEnvPath()) {
		if os.Getenv(key) == "" {
			os.Setenv(key, val)
		}
	}
}

func maskValue(val string) string {
	if len(val) <= 6 {
		return "***"
	}
	return "***" + val[len(val)-4:]
}

// summarizeSettingsFile returns a one-line summary of the contents of a
// known settings file. Returns "" for unknown filenames.
func summarizeSettingsFile(name string, settings *Settings) string {
	switch name {
	case "config.env":
		env := loadConfigEnv(configEnvPath())
		if len(env) == 0 {
			return "(empty)"
		}
		keys := make([]string, 0, len(env))
		for k := range env {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		return fmt.Sprintf("%d keys: %s", len(keys), strings.Join(keys, ", "))

	case "settings.json":
		if settings == nil {
			return "(unable to load)"
		}
		var parts []string
		if settings.Discord.GuildID != "" {
			parts = append(parts, "discord")
		}
		if settings.ContributionToken != nil && settings.ContributionToken.Symbol != "" {
			parts = append(parts, fmt.Sprintf("token %s", settings.ContributionToken.Symbol))
		}
		if settings.Membership.Stripe.ProductID != "" {
			parts = append(parts, "stripe membership")
		}
		if len(settings.Membership.Odoo.Products) > 0 {
			parts = append(parts, fmt.Sprintf("%d odoo products", len(settings.Membership.Odoo.Products)))
		}
		if settings.Accounting != nil && settings.Accounting.Odoo != nil && len(settings.Accounting.Odoo.CategoryMapping) > 0 {
			parts = append(parts, fmt.Sprintf("%d odoo→category mappings", len(settings.Accounting.Odoo.CategoryMapping)))
		}
		if len(parts) == 0 {
			return "(no recognized keys)"
		}
		return strings.Join(parts, ", ")

	case "accounts.json":
		configs := LoadAccountConfigs()
		if len(configs) == 0 {
			return "(empty)"
		}
		byProvider := map[string]int{}
		for _, c := range configs {
			p := c.Provider
			if p == "" {
				p = "unknown"
			}
			byProvider[p]++
		}
		providers := make([]string, 0, len(byProvider))
		for p := range byProvider {
			providers = append(providers, p)
		}
		sort.Strings(providers)
		details := make([]string, 0, len(providers))
		for _, p := range providers {
			details = append(details, fmt.Sprintf("%d %s", byProvider[p], p))
		}
		return fmt.Sprintf("%d accounts (%s)", len(configs), strings.Join(details, ", "))

	case "calendars.json":
		if settings == nil {
			return "(unable to load)"
		}
		sources := settings.Calendars.Sources
		if len(sources) == 0 {
			return "(empty)"
		}
		slugs := make([]string, 0, len(sources))
		for _, s := range sources {
			slugs = append(slugs, s.Slug)
		}
		return fmt.Sprintf("%d sources: %s", len(sources), strings.Join(slugs, ", "))

	case "categories.json":
		cats := LoadCategories()
		income, expense := 0, 0
		for _, c := range cats {
			switch c.Direction {
			case "income":
				income++
			case "expense":
				expense++
			}
		}
		return fmt.Sprintf("%d categories (%d income, %d expense)", len(cats), income, expense)

	case "collectives.json":
		c := LoadCollectives()
		if len(c) == 0 {
			return "(empty)"
		}
		slugs := make([]string, 0, len(c))
		for k := range c {
			slugs = append(slugs, k)
		}
		sort.Strings(slugs)
		return fmt.Sprintf("%d collectives: %s", len(slugs), strings.Join(slugs, ", "))

	case "nostr.json":
		keys := LoadNostrKeys()
		if keys == nil {
			return "(not configured)"
		}
		npub := keys.Npub
		if len(npub) > 24 {
			npub = npub[:20] + "…"
		}
		name := ""
		if keys.Name != "" {
			name = fmt.Sprintf(" (%s)", keys.Name)
		}
		return fmt.Sprintf("%s%s, %d relay(s)", npub, name, len(keys.Relays))

	case "rooms.json":
		rooms, _ := LoadRooms()
		return fmt.Sprintf("%d rooms", len(rooms))

	case "rules.json":
		rules, _ := LoadRules()
		return fmt.Sprintf("%d rules", len(rules))

	case "tokens.json":
		tokens := LoadTokenConfigs()
		if len(tokens) == 0 {
			return "(empty)"
		}
		symbols := make([]string, 0, len(tokens))
		for _, t := range tokens {
			symbols = append(symbols, t.Symbol)
		}
		return fmt.Sprintf("%d tokens: %s", len(tokens), strings.Join(symbols, ", "))
	}
	return ""
}
