package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type envKey struct {
	Name string
	Desc string
	Help string // URL or hint for getting the key
}

var envKeys = []envKey{
	{"LUMA_API_KEY", "Luma calendar (event sync)", "https://docs.lu.ma/reference/getting-started"},
	{"ETHERSCAN_API_KEY", "Gnosisscan (transaction sync)", "https://gnosisscan.io/myapikey"},
	{"DISCORD_BOT_TOKEN", "Discord (message sync)", "https://discord.com/developers/applications"},
	{"STRIPE_SECRET_KEY", "Stripe (member/transaction sync)", "https://dashboard.stripe.com/apikeys"},
	{"MONERIUM_CLIENT_ID", "Monerium OAuth client ID", "https://monerium.dev/docs/getting-started"},
	{"MONERIUM_CLIENT_SECRET", "Monerium OAuth client secret", "https://monerium.dev/docs/getting-started"},
	{"ODOO_URL", "Odoo instance URL (member sync)", "e.g. https://mycompany.odoo.com"},
	{"ODOO_LOGIN", "Odoo login email (member sync)", "The email you use to log into Odoo"},
	{"ODOO_PASSWORD", "Odoo password or API key (member sync)", "Settings → API Keys (or your password)"},
}

// Setup runs the interactive key configuration wizard
func Setup() error {
	configPath := configEnvPath()
	existing := loadConfigEnv(configPath)
	reader := bufio.NewReader(os.Stdin)

	for {
		fmt.Printf("\n%sCommons Hub CLI Setup%s\n", Fmt.Bold, Fmt.Reset)
		fmt.Println("─────────────────────")
		fmt.Println()

		for i, k := range envKeys {
			status := fmt.Sprintf("%s☐%s", Fmt.Dim, Fmt.Reset)
			if val, ok := existing[k.Name]; ok && val != "" {
				status = fmt.Sprintf("%s✓%s", Fmt.Green, Fmt.Reset)
			}
			fmt.Printf("  %d. %s  %-22s %s%s%s\n", i+1, status, k.Name, Fmt.Dim, k.Desc, Fmt.Reset)
		}

		fmt.Println()
		fmt.Printf("Select key to configure (1-%d), or q to quit: ", len(envKeys))
		input, _ := reader.ReadString('\n')
		input = strings.TrimSpace(input)

		if input == "q" || input == "Q" || input == "" {
			fmt.Println()
			return nil
		}

		idx := 0
		if _, err := fmt.Sscanf(input, "%d", &idx); err != nil || idx < 1 || idx > len(envKeys) {
			fmt.Printf("%sInvalid selection%s\n", Fmt.Red, Fmt.Reset)
			continue
		}

		k := envKeys[idx-1]
		fmt.Println()
		fmt.Printf("%s%s%s\n", Fmt.Bold, k.Name, Fmt.Reset)
		fmt.Printf("  %s%s%s\n", Fmt.Dim, k.Desc, Fmt.Reset)
		if k.Help != "" {
			fmt.Printf("  Get one at: %s%s%s\n", Fmt.Cyan, k.Help, Fmt.Reset)
		}

		// Show current value masked if set
		if val, ok := existing[k.Name]; ok && val != "" {
			masked := maskValue(val)
			fmt.Printf("  Current: %s%s%s\n", Fmt.Dim, masked, Fmt.Reset)
		}

		fmt.Println()
		fmt.Printf("  Paste key (or Enter to cancel): ")
		value, _ := reader.ReadString('\n')
		value = strings.TrimSpace(value)

		// Overwrite the input line to hide the pasted secret
		if value != "" {
			fmt.Printf("\033[1A\033[2K  Paste key (or Enter to cancel): %s\n", maskValue(value))
		}

		if value == "" {
			continue
		}

		existing[k.Name] = value
		if err := saveConfigEnv(configPath, existing); err != nil {
			fmt.Printf("  %sError saving:%s %v\n", Fmt.Red, Fmt.Reset, err)
			continue
		}

		fmt.Printf("  %s✓ Saved %s%s = %s%s%s\n", Fmt.Green, k.Name, Fmt.Reset, Fmt.Dim, maskValue(value), Fmt.Reset)
	}
}

func configEnvPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(".", ".chb", "config.env")
	}
	return filepath.Join(home, ".chb", "config.env")
}

func loadConfigEnv(path string) map[string]string {
	result := make(map[string]string)
	data, err := os.ReadFile(path)
	if err != nil {
		return result
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			val := strings.TrimSpace(parts[1])
			// Strip surrounding quotes
			val = strings.Trim(val, "\"'")
			result[key] = val
		}
	}
	return result
}

func saveConfigEnv(path string, env map[string]string) error {
	dir := filepath.Dir(path)
	os.MkdirAll(dir, 0755)

	var lines []string
	lines = append(lines, "# Commons Hub CLI configuration")
	lines = append(lines, "# Generated by: chb setup")
	lines = append(lines, "")

	for _, k := range envKeys {
		if val, ok := env[k.Name]; ok && val != "" {
			lines = append(lines, fmt.Sprintf("%s=%s", k.Name, val))
		}
	}
	lines = append(lines, "")

	return os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0600)
}

// LoadEnvFromConfig loads ~/.chb/config.env into os environment (if not already set)
func LoadEnvFromConfig() {
	env := loadConfigEnv(configEnvPath())
	for key, val := range env {
		if os.Getenv(key) == "" {
			os.Setenv(key, val)
		}
	}
}

func maskValue(val string) string {
	if len(val) <= 6 {
		return "***"
	}
	return "***" + val[len(val)-4:]
}
